import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import {
    categories,
    folders,
    tools,
    walletItems,
} from "./components/SidebarContents";
import PremiumBox from "./components/PremiumBox";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-customDark-100 flex flex-col h-screen`}
            >
                <Navbar />
                <div className="">
                    <Sidebar
                        categories={categories}
                        walletItems={walletItems}
                        folders={folders}
                        tools={tools}
                    />
                </div>

                <div className="flex-1">
                    <PremiumBox />
                    {children}
                </div>
            </body>
        </html>
    );
}
